language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
before_install:
  - gem install bundler
before_script:
  - sudo apt-get install pdftk
script:
  - bundle exec rake test
notifications:
  email:
    - trung.le@ruby-journal.com
